export const FEATURES = {
  'wellhead-analytics': {
    title: 'Wellhead Analytics',
    description: 'Real-time wellhead monitoring with pressure, temperature, and flow analysis',
    icon: 'GiOilPump',
    color: '#3B82F6',
    gradient: 'linear-gradient(135deg, #1E3A5F 0%, #3B82F6 100%)',
    endpoint: '/wellhead-analytics',
    aiType: 'wellhead',
    fields: [
      { key: 'well_name', label: 'Well Name', type: 'text', required: true },
      { key: 'location', label: 'Location', type: 'text' },
      { key: 'latitude', label: 'Latitude', type: 'number' },
      { key: 'longitude', label: 'Longitude', type: 'number' },
      { key: 'well_type', label: 'Well Type', type: 'select', options: ['Horizontal', 'Vertical', 'Directional'] },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'Inactive', 'Shut-in'] },
      { key: 'pressure_psi', label: 'Pressure (PSI)', type: 'number' },
      { key: 'temperature_f', label: 'Temperature (F)', type: 'number' },
      { key: 'flow_rate_bpd', label: 'Flow Rate (BPD)', type: 'number' },
      { key: 'gas_oil_ratio', label: 'Gas-Oil Ratio', type: 'number' },
      { key: 'water_cut_pct', label: 'Water Cut (%)', type: 'number' },
      { key: 'choke_size', label: 'Choke Size', type: 'text' },
    ],
    columns: ['well_name', 'location', 'well_type', 'status', 'pressure_psi', 'flow_rate_bpd', 'water_cut_pct'],
    columnLabels: { well_name: 'Well Name', location: 'Location', well_type: 'Type', status: 'Status', pressure_psi: 'Pressure (PSI)', flow_rate_bpd: 'Flow Rate (BPD)', water_cut_pct: 'Water Cut (%)' }
  },
  'reservoir-simulation': {
    title: 'Reservoir Simulation',
    description: 'Advanced reservoir modeling with porosity, permeability, and recovery analysis',
    icon: 'GiUndergroundCave',
    color: '#8B5CF6',
    gradient: 'linear-gradient(135deg, #4C1D95 0%, #8B5CF6 100%)',
    endpoint: '/reservoir-simulation',
    aiType: 'reservoir',
    fields: [
      { key: 'reservoir_name', label: 'Reservoir Name', type: 'text', required: true },
      { key: 'field_name', label: 'Field Name', type: 'text' },
      { key: 'depth_ft', label: 'Depth (ft)', type: 'number' },
      { key: 'porosity_pct', label: 'Porosity (%)', type: 'number' },
      { key: 'permeability_md', label: 'Permeability (mD)', type: 'number' },
      { key: 'fluid_type', label: 'Fluid Type', type: 'select', options: ['Black Oil', 'Volatile Oil', 'Gas Condensate', 'Dry Gas', 'Wet Gas', 'Heavy Oil', 'Light Oil'] },
      { key: 'reservoir_pressure_psi', label: 'Pressure (PSI)', type: 'number' },
      { key: 'temperature_f', label: 'Temperature (F)', type: 'number' },
      { key: 'oil_saturation_pct', label: 'Oil Saturation (%)', type: 'number' },
      { key: 'gas_saturation_pct', label: 'Gas Saturation (%)', type: 'number' },
      { key: 'water_saturation_pct', label: 'Water Saturation (%)', type: 'number' },
      { key: 'recovery_factor_pct', label: 'Recovery Factor (%)', type: 'number' },
      { key: 'simulation_model', label: 'Simulation Model', type: 'select', options: ['Black Oil', 'Compositional', 'Dual Porosity', 'Thermal'] },
    ],
    columns: ['reservoir_name', 'field_name', 'depth_ft', 'fluid_type', 'porosity_pct', 'permeability_md', 'recovery_factor_pct'],
    columnLabels: { reservoir_name: 'Reservoir', field_name: 'Field', depth_ft: 'Depth (ft)', fluid_type: 'Fluid', porosity_pct: 'Porosity (%)', permeability_md: 'Perm (mD)', recovery_factor_pct: 'Recovery (%)' }
  },
  'decline-curves': {
    title: 'Production Decline Curves',
    description: 'Decline curve analysis with Arps models for production forecasting',
    icon: 'GiChart',
    color: '#EF4444',
    gradient: 'linear-gradient(135deg, #991B1B 0%, #EF4444 100%)',
    endpoint: '/decline-curves',
    aiType: 'decline-curve',
    fields: [
      { key: 'well_name', label: 'Well Name', type: 'text', required: true },
      { key: 'field_name', label: 'Field Name', type: 'text' },
      { key: 'initial_rate_bpd', label: 'Initial Rate (BPD)', type: 'number' },
      { key: 'current_rate_bpd', label: 'Current Rate (BPD)', type: 'number' },
      { key: 'decline_rate_pct', label: 'Decline Rate (%)', type: 'number' },
      { key: 'decline_type', label: 'Decline Type', type: 'select', options: ['Exponential', 'Hyperbolic', 'Harmonic'] },
      { key: 'b_factor', label: 'B-Factor', type: 'number' },
      { key: 'economic_limit_bpd', label: 'Economic Limit (BPD)', type: 'number' },
      { key: 'estimated_reserves_bbl', label: 'Estimated Reserves (BBL)', type: 'number' },
      { key: 'production_start_date', label: 'Production Start', type: 'date' },
      { key: 'time_to_abandonment_months', label: 'Time to Abandonment (months)', type: 'number' },
    ],
    columns: ['well_name', 'field_name', 'initial_rate_bpd', 'current_rate_bpd', 'decline_rate_pct', 'decline_type', 'estimated_reserves_bbl'],
    columnLabels: { well_name: 'Well', field_name: 'Field', initial_rate_bpd: 'Initial (BPD)', current_rate_bpd: 'Current (BPD)', decline_rate_pct: 'Decline (%)', decline_type: 'Type', estimated_reserves_bbl: 'Reserves (BBL)' }
  },
  'equipment-failure': {
    title: 'Equipment Failure Prediction',
    description: 'Predictive maintenance and failure analysis for field equipment',
    icon: 'GiGears',
    color: '#F59E0B',
    gradient: 'linear-gradient(135deg, #92400E 0%, #F59E0B 100%)',
    endpoint: '/equipment-failure',
    aiType: 'equipment',
    fields: [
      { key: 'equipment_name', label: 'Equipment Name', type: 'text', required: true },
      { key: 'equipment_type', label: 'Equipment Type', type: 'select', options: ['Electric Submersible Pump', 'Sucker Rod Pump', 'Progressive Cavity Pump', 'Gas Compressor', 'Separator', 'Christmas Tree', 'Safety Valve', 'Line Heater', 'Flow Meter', 'Storage Tank', 'Plunger Lift', 'Dehydrator', 'Generator', 'Hydraulic Pump', 'Chemical Injection Pump'] },
      { key: 'well_name', label: 'Well Name', type: 'text' },
      { key: 'manufacturer', label: 'Manufacturer', type: 'text' },
      { key: 'install_date', label: 'Install Date', type: 'date' },
      { key: 'last_maintenance_date', label: 'Last Maintenance', type: 'date' },
      { key: 'operating_hours', label: 'Operating Hours', type: 'number' },
      { key: 'health_score', label: 'Health Score (0-100)', type: 'number' },
      { key: 'failure_probability_pct', label: 'Failure Probability (%)', type: 'number' },
      { key: 'vibration_level', label: 'Vibration Level', type: 'select', options: ['Low', 'Medium', 'High'] },
      { key: 'temperature_f', label: 'Temperature (F)', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['Operational', 'Warning', 'Critical'] },
      { key: 'next_maintenance_date', label: 'Next Maintenance', type: 'date' },
    ],
    columns: ['equipment_name', 'equipment_type', 'well_name', 'health_score', 'failure_probability_pct', 'status'],
    columnLabels: { equipment_name: 'Equipment', equipment_type: 'Type', well_name: 'Well', health_score: 'Health', failure_probability_pct: 'Failure (%)', status: 'Status' }
  },
  'environmental-compliance': {
    title: 'Environmental Compliance',
    description: 'Environmental monitoring, emissions tracking, and regulatory compliance',
    icon: 'GiEcology',
    color: '#10B981',
    gradient: 'linear-gradient(135deg, #064E3B 0%, #10B981 100%)',
    endpoint: '/environmental-compliance',
    aiType: 'environmental',
    fields: [
      { key: 'well_name', label: 'Well Name', type: 'text', required: true },
      { key: 'site_name', label: 'Site Name', type: 'text' },
      { key: 'emission_type', label: 'Emission Type', type: 'select', options: ['Methane', 'VOC', 'CO2', 'H2S', 'Flaring', 'PM2.5', 'Benzene', 'NOx', 'Produced Water', 'SOx', 'Groundwater', 'Noise', 'Spill Risk'] },
      { key: 'emission_level', label: 'Emission Level', type: 'number' },
      { key: 'emission_unit', label: 'Unit', type: 'text' },
      { key: 'regulatory_threshold', label: 'Regulatory Threshold', type: 'number' },
      { key: 'compliance_status', label: 'Compliance Status', type: 'select', options: ['Compliant', 'Non-Compliant'] },
      { key: 'inspection_date', label: 'Inspection Date', type: 'date' },
      { key: 'inspector_name', label: 'Inspector', type: 'text' },
      { key: 'corrective_action', label: 'Corrective Action', type: 'text' },
      { key: 'penalty_amount', label: 'Penalty ($)', type: 'number' },
      { key: 'next_inspection_date', label: 'Next Inspection', type: 'date' },
    ],
    columns: ['well_name', 'site_name', 'emission_type', 'emission_level', 'compliance_status', 'penalty_amount'],
    columnLabels: { well_name: 'Well', site_name: 'Site', emission_type: 'Emission', emission_level: 'Level', compliance_status: 'Status', penalty_amount: 'Penalty ($)' }
  },
  'production-forecasting': {
    title: 'Production Forecasting',
    description: 'AI-powered production rate predictions and revenue forecasting',
    icon: 'GiCrystalBall',
    color: '#06B6D4',
    gradient: 'linear-gradient(135deg, #164E63 0%, #06B6D4 100%)',
    endpoint: '/production-forecasting',
    aiType: 'forecast',
    fields: [
      { key: 'well_name', label: 'Well Name', type: 'text', required: true },
      { key: 'field_name', label: 'Field Name', type: 'text' },
      { key: 'current_rate_bpd', label: 'Current Rate (BPD)', type: 'number' },
      { key: 'forecast_period_months', label: 'Forecast Period (months)', type: 'number' },
      { key: 'predicted_rate_bpd', label: 'Predicted Rate (BPD)', type: 'number' },
      { key: 'predicted_cumulative_bbl', label: 'Predicted Cumulative (BBL)', type: 'number' },
      { key: 'confidence_pct', label: 'Confidence (%)', type: 'number' },
      { key: 'forecast_method', label: 'Forecast Method', type: 'select', options: ['Arps Decline', 'Type Curve', 'Machine Learning', 'Material Balance', 'Reservoir Sim'] },
      { key: 'oil_price_usd', label: 'Oil Price ($/BBL)', type: 'number' },
      { key: 'estimated_revenue_usd', label: 'Est. Revenue ($)', type: 'number' },
      { key: 'risk_factor', label: 'Risk Factor', type: 'select', options: ['Low', 'Medium', 'High'] },
    ],
    columns: ['well_name', 'current_rate_bpd', 'predicted_rate_bpd', 'confidence_pct', 'forecast_method', 'estimated_revenue_usd', 'risk_factor'],
    columnLabels: { well_name: 'Well', current_rate_bpd: 'Current (BPD)', predicted_rate_bpd: 'Predicted (BPD)', confidence_pct: 'Confidence (%)', forecast_method: 'Method', estimated_revenue_usd: 'Revenue ($)', risk_factor: 'Risk' }
  },
  'well-performance': {
    title: 'Well Performance Monitoring',
    description: 'Comprehensive well performance metrics and optimization analytics',
    icon: 'GiSpeedometer',
    color: '#EC4899',
    gradient: 'linear-gradient(135deg, #831843 0%, #EC4899 100%)',
    endpoint: '/well-performance',
    aiType: 'performance',
    fields: [
      { key: 'well_name', label: 'Well Name', type: 'text', required: true },
      { key: 'field_name', label: 'Field Name', type: 'text' },
      { key: 'oil_rate_bpd', label: 'Oil Rate (BPD)', type: 'number' },
      { key: 'gas_rate_mcfd', label: 'Gas Rate (MCFD)', type: 'number' },
      { key: 'water_rate_bpd', label: 'Water Rate (BPD)', type: 'number' },
      { key: 'water_cut_pct', label: 'Water Cut (%)', type: 'number' },
      { key: 'gas_oil_ratio', label: 'Gas-Oil Ratio', type: 'number' },
      { key: 'bottom_hole_pressure_psi', label: 'BHP (PSI)', type: 'number' },
      { key: 'tubing_pressure_psi', label: 'Tubing Pressure (PSI)', type: 'number' },
      { key: 'casing_pressure_psi', label: 'Casing Pressure (PSI)', type: 'number' },
      { key: 'uptime_pct', label: 'Uptime (%)', type: 'number' },
      { key: 'efficiency_pct', label: 'Efficiency (%)', type: 'number' },
    ],
    columns: ['well_name', 'field_name', 'oil_rate_bpd', 'gas_rate_mcfd', 'water_cut_pct', 'uptime_pct', 'efficiency_pct'],
    columnLabels: { well_name: 'Well', field_name: 'Field', oil_rate_bpd: 'Oil (BPD)', gas_rate_mcfd: 'Gas (MCFD)', water_cut_pct: 'Water Cut (%)', uptime_pct: 'Uptime (%)', efficiency_pct: 'Efficiency (%)' }
  },
  'drilling-operations': {
    title: 'Drilling Operations',
    description: 'Real-time drilling parameter tracking with ROP, WOB, torque, and mud analysis',
    icon: 'GiDrill',
    color: '#F97316',
    gradient: 'linear-gradient(135deg, #7C2D12 0%, #F97316 100%)',
    endpoint: '/drilling-operations',
    aiType: 'drilling',
    fields: [
      { key: 'well_name', label: 'Well Name', type: 'text', required: true },
      { key: 'rig_name', label: 'Rig Name', type: 'text' },
      { key: 'operator', label: 'Operator', type: 'text' },
      { key: 'field_name', label: 'Field Name', type: 'text' },
      { key: 'spud_date', label: 'Spud Date', type: 'date' },
      { key: 'current_depth_ft', label: 'Current Depth (ft)', type: 'number' },
      { key: 'target_depth_ft', label: 'Target Depth (ft)', type: 'number' },
      { key: 'rop_ft_hr', label: 'ROP (ft/hr)', type: 'number' },
      { key: 'wob_klb', label: 'WOB (klb)', type: 'number' },
      { key: 'torque_ft_lb', label: 'Torque (ft-lb)', type: 'number' },
      { key: 'rpm', label: 'RPM', type: 'number' },
      { key: 'mud_weight_ppg', label: 'Mud Weight (ppg)', type: 'number' },
      { key: 'mud_type', label: 'Mud Type', type: 'select', options: ['Water-Based', 'Oil-Based', 'Synthetic'] },
      { key: 'bit_type', label: 'Bit Type', type: 'select', options: ['PDC', 'Roller Cone', 'Hybrid', 'Diamond'] },
      { key: 'bit_size_in', label: 'Bit Size (in)', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['Drilling', 'Completing', 'Completed', 'Suspended'] },
    ],
    columns: ['well_name', 'rig_name', 'operator', 'current_depth_ft', 'rop_ft_hr', 'mud_weight_ppg', 'status'],
    columnLabels: { well_name: 'Well', rig_name: 'Rig', operator: 'Operator', current_depth_ft: 'Depth (ft)', rop_ft_hr: 'ROP (ft/hr)', mud_weight_ppg: 'Mud (ppg)', status: 'Status' }
  },
  'cost-analysis': {
    title: 'Cost Analysis & Economics',
    description: 'CAPEX/OPEX tracking, NPV, IRR, breakeven analysis, and revenue forecasting',
    icon: 'GiMoneyStack',
    color: '#14B8A6',
    gradient: 'linear-gradient(135deg, #134E4A 0%, #14B8A6 100%)',
    endpoint: '/cost-analysis',
    aiType: 'cost',
    fields: [
      { key: 'well_name', label: 'Well Name', type: 'text', required: true },
      { key: 'field_name', label: 'Field Name', type: 'text' },
      { key: 'capex_usd', label: 'CAPEX ($)', type: 'number' },
      { key: 'opex_monthly_usd', label: 'Monthly OPEX ($)', type: 'number' },
      { key: 'drilling_cost_usd', label: 'Drilling Cost ($)', type: 'number' },
      { key: 'completion_cost_usd', label: 'Completion Cost ($)', type: 'number' },
      { key: 'npv_usd', label: 'NPV ($)', type: 'number' },
      { key: 'irr_pct', label: 'IRR (%)', type: 'number' },
      { key: 'payback_months', label: 'Payback (months)', type: 'number' },
      { key: 'breakeven_price_usd', label: 'Breakeven ($/BBL)', type: 'number' },
      { key: 'oil_price_usd', label: 'Oil Price ($/BBL)', type: 'number' },
      { key: 'production_rate_bpd', label: 'Production (BPD)', type: 'number' },
      { key: 'operating_margin_pct', label: 'Operating Margin (%)', type: 'number' },
      { key: 'project_status', label: 'Project Status', type: 'select', options: ['Producing', 'Drilling', 'Shut-in', 'Planning', 'Abandoned'] },
    ],
    columns: ['well_name', 'capex_usd', 'npv_usd', 'irr_pct', 'breakeven_price_usd', 'operating_margin_pct', 'project_status'],
    columnLabels: { well_name: 'Well', capex_usd: 'CAPEX ($)', npv_usd: 'NPV ($)', irr_pct: 'IRR (%)', breakeven_price_usd: 'Breakeven ($)', operating_margin_pct: 'Margin (%)', project_status: 'Status' }
  },
  'pipeline-monitoring': {
    title: 'Pipeline Monitoring',
    description: 'Pipeline integrity tracking, corrosion monitoring, and leak detection analytics',
    icon: 'GiPipes',
    color: '#6366F1',
    gradient: 'linear-gradient(135deg, #312E81 0%, #6366F1 100%)',
    endpoint: '/pipeline-monitoring',
    aiType: 'pipeline',
    fields: [
      { key: 'pipeline_name', label: 'Pipeline Name', type: 'text', required: true },
      { key: 'segment_id', label: 'Segment ID', type: 'text' },
      { key: 'origin', label: 'Origin', type: 'text' },
      { key: 'destination', label: 'Destination', type: 'text' },
      { key: 'length_miles', label: 'Length (miles)', type: 'number' },
      { key: 'diameter_in', label: 'Diameter (in)', type: 'number' },
      { key: 'material', label: 'Material', type: 'select', options: ['Carbon Steel', 'Steel Alloy', 'Stainless Steel', 'HDPE'] },
      { key: 'max_pressure_psi', label: 'Max Pressure (PSI)', type: 'number' },
      { key: 'current_pressure_psi', label: 'Current Pressure (PSI)', type: 'number' },
      { key: 'flow_rate_bpd', label: 'Flow Rate (BPD)', type: 'number' },
      { key: 'fluid_type', label: 'Fluid Type', type: 'select', options: ['Crude Oil', 'Natural Gas', 'Mixed', 'Water', 'NGL'] },
      { key: 'wall_thickness_in', label: 'Wall Thickness (in)', type: 'number' },
      { key: 'corrosion_rate_mpy', label: 'Corrosion Rate (mpy)', type: 'number' },
      { key: 'last_inspection_date', label: 'Last Inspection', type: 'date' },
      { key: 'integrity_status', label: 'Integrity Status', type: 'select', options: ['Good', 'Fair', 'Warning', 'Critical'] },
    ],
    columns: ['pipeline_name', 'segment_id', 'origin', 'destination', 'corrosion_rate_mpy', 'integrity_status'],
    columnLabels: { pipeline_name: 'Pipeline', segment_id: 'Segment', origin: 'Origin', destination: 'Destination', corrosion_rate_mpy: 'Corrosion (mpy)', integrity_status: 'Status' }
  },
  'water-management': {
    title: 'Water Management',
    description: 'Produced water tracking, disposal management, and treatment optimization',
    icon: 'GiWaterDrop',
    color: '#0EA5E9',
    gradient: 'linear-gradient(135deg, #0C4A6E 0%, #0EA5E9 100%)',
    endpoint: '/water-management',
    aiType: 'water',
    fields: [
      { key: 'well_name', label: 'Well Name', type: 'text', required: true },
      { key: 'field_name', label: 'Field Name', type: 'text' },
      { key: 'produced_water_bpd', label: 'Produced Water (BPD)', type: 'number' },
      { key: 'injected_water_bpd', label: 'Injected Water (BPD)', type: 'number' },
      { key: 'disposal_method', label: 'Disposal Method', type: 'select', options: ['Injection', 'Trucking', 'Evaporation Pond', 'Treatment & Reuse', 'N/A'] },
      { key: 'treatment_type', label: 'Treatment Type', type: 'text' },
      { key: 'tds_ppm', label: 'TDS (ppm)', type: 'number' },
      { key: 'ph_level', label: 'pH Level', type: 'number' },
      { key: 'oil_in_water_ppm', label: 'Oil in Water (ppm)', type: 'number' },
      { key: 'disposal_well_name', label: 'Disposal Well', type: 'text' },
      { key: 'injection_pressure_psi', label: 'Injection Pressure (PSI)', type: 'number' },
      { key: 'water_source', label: 'Water Source', type: 'select', options: ['Produced', 'Recycled', 'Fresh', 'N/A'] },
      { key: 'recycled_pct', label: 'Recycled (%)', type: 'number' },
      { key: 'cost_per_bbl_usd', label: 'Cost ($/BBL)', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'Warning', 'Inactive'] },
    ],
    columns: ['well_name', 'produced_water_bpd', 'disposal_method', 'tds_ppm', 'recycled_pct', 'cost_per_bbl_usd', 'status'],
    columnLabels: { well_name: 'Well', produced_water_bpd: 'Produced (BPD)', disposal_method: 'Disposal', tds_ppm: 'TDS (ppm)', recycled_pct: 'Recycled (%)', cost_per_bbl_usd: 'Cost ($/BBL)', status: 'Status' }
  },
  'safety-incidents': {
    title: 'Safety Incident Tracking',
    description: 'HSE incident reporting, root cause analysis, and safety metrics dashboard',
    icon: 'GiWarningSign',
    color: '#DC2626',
    gradient: 'linear-gradient(135deg, #7F1D1D 0%, #DC2626 100%)',
    endpoint: '/safety-incidents',
    aiType: 'safety',
    fields: [
      { key: 'incident_title', label: 'Incident Title', type: 'text', required: true },
      { key: 'site_name', label: 'Site Name', type: 'text' },
      { key: 'well_name', label: 'Well Name', type: 'text' },
      { key: 'incident_date', label: 'Incident Date', type: 'date' },
      { key: 'incident_type', label: 'Incident Type', type: 'select', options: ['Gas Release', 'Slip/Trip/Fall', 'Pressure Event', 'Vehicle Accident', 'Chemical Exposure', 'Fire', 'Dropped Object', 'Confined Space', 'Wildlife/Insect', 'Well Control', 'Noise Exposure', 'Spill/Leak', 'Heat Illness', 'Equipment Failure', 'Vehicle Near Miss'] },
      { key: 'severity', label: 'Severity', type: 'select', options: ['Low', 'Medium', 'High', 'Critical'] },
      { key: 'description', label: 'Description', type: 'text' },
      { key: 'root_cause', label: 'Root Cause', type: 'text' },
      { key: 'corrective_action', label: 'Corrective Action', type: 'text' },
      { key: 'injuries_count', label: 'Injuries', type: 'number' },
      { key: 'days_lost', label: 'Days Lost', type: 'number' },
      { key: 'reported_by', label: 'Reported By', type: 'text' },
      { key: 'investigation_status', label: 'Investigation Status', type: 'select', options: ['Open', 'In Progress', 'Closed'] },
      { key: 'osha_recordable', label: 'OSHA Recordable', type: 'select', options: ['Yes', 'No'] },
    ],
    columns: ['incident_title', 'site_name', 'incident_type', 'severity', 'injuries_count', 'investigation_status'],
    columnLabels: { incident_title: 'Incident', site_name: 'Site', incident_type: 'Type', severity: 'Severity', injuries_count: 'Injuries', investigation_status: 'Status' }
  },
  'gas-lift-optimization': {
    title: 'Gas Lift Optimization',
    description: 'Gas lift performance analysis, injection rate optimization, and valve design',
    icon: 'GiGasStove',
    color: '#A855F7',
    gradient: 'linear-gradient(135deg, #581C87 0%, #A855F7 100%)',
    endpoint: '/gas-lift-optimization',
    aiType: 'gaslift',
    fields: [
      { key: 'well_name', label: 'Well Name', type: 'text', required: true },
      { key: 'field_name', label: 'Field Name', type: 'text' },
      { key: 'injection_rate_mcfd', label: 'Injection Rate (MCFD)', type: 'number' },
      { key: 'injection_pressure_psi', label: 'Injection Pressure (PSI)', type: 'number' },
      { key: 'oil_rate_before_bpd', label: 'Oil Rate Before (BPD)', type: 'number' },
      { key: 'oil_rate_after_bpd', label: 'Oil Rate After (BPD)', type: 'number' },
      { key: 'gas_source', label: 'Gas Source', type: 'select', options: ['Field Gas', 'Purchased', 'N/A'] },
      { key: 'valve_count', label: 'Valve Count', type: 'number' },
      { key: 'deepest_valve_depth_ft', label: 'Deepest Valve Depth (ft)', type: 'number' },
      { key: 'casing_pressure_psi', label: 'Casing Pressure (PSI)', type: 'number' },
      { key: 'tubing_pressure_psi', label: 'Tubing Pressure (PSI)', type: 'number' },
      { key: 'glr_scf_bbl', label: 'GLR (SCF/BBL)', type: 'number' },
      { key: 'optimization_status', label: 'Optimization Status', type: 'select', options: ['Optimized', 'Active', 'Needs Review', 'Planned', 'Inactive'] },
      { key: 'cost_per_mcf_usd', label: 'Gas Cost ($/MCF)', type: 'number' },
      { key: 'incremental_revenue_usd', label: 'Incremental Revenue ($)', type: 'number' },
    ],
    columns: ['well_name', 'injection_rate_mcfd', 'oil_rate_before_bpd', 'oil_rate_after_bpd', 'valve_count', 'incremental_revenue_usd', 'optimization_status'],
    columnLabels: { well_name: 'Well', injection_rate_mcfd: 'Injection (MCFD)', oil_rate_before_bpd: 'Before (BPD)', oil_rate_after_bpd: 'After (BPD)', valve_count: 'Valves', incremental_revenue_usd: 'Revenue ($)', optimization_status: 'Status' }
  }
};
