export const OPERATION_RESOURCES = {
  'work-orders': {
    title: 'Work Orders',
    description: 'Create, assign, prioritize, and track operational work through completion.',
    color: '#38BDF8',
    primary: 'title',
    columns: ['title', 'well_name', 'asset_tag', 'priority', 'status', 'assigned_to', 'due_date'],
    fields: [
      { key: 'title', label: 'Title', required: true },
      { key: 'well_name', label: 'Well Name' },
      { key: 'asset_tag', label: 'Asset Tag' },
      { key: 'priority', label: 'Priority', type: 'select', options: ['Low', 'Medium', 'High', 'Critical'] },
      { key: 'status', label: 'Status', type: 'select', options: ['Open', 'Assigned', 'In Progress', 'Waiting Parts', 'Completed', 'Cancelled'] },
      { key: 'assigned_to', label: 'Assigned To' },
      { key: 'due_date', label: 'Due Date', type: 'date' },
      { key: 'estimated_cost_usd', label: 'Estimated Cost ($)', type: 'number' },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  assets: {
    title: 'Asset Registry',
    description: 'Track equipment lifecycle, criticality, replacement dates, and field assignment.',
    color: '#A78BFA',
    primary: 'asset_name',
    columns: ['asset_tag', 'asset_name', 'asset_type', 'well_name', 'lifecycle_status', 'criticality', 'replacement_due_date'],
    fields: [
      { key: 'asset_tag', label: 'Asset Tag', required: true },
      { key: 'asset_name', label: 'Asset Name', required: true },
      { key: 'asset_type', label: 'Asset Type', type: 'select', options: ['Pump', 'Compressor', 'Separator', 'Valve', 'Pipeline', 'Tank', 'Meter', 'Generator', 'RTU'] },
      { key: 'well_name', label: 'Well Name' },
      { key: 'manufacturer', label: 'Manufacturer' },
      { key: 'install_date', label: 'Install Date', type: 'date' },
      { key: 'lifecycle_status', label: 'Lifecycle Status', type: 'select', options: ['Planned', 'In Service', 'Maintenance', 'Retired', 'Decommissioned'] },
      { key: 'criticality', label: 'Criticality', type: 'select', options: ['Low', 'Medium', 'High', 'Critical'] },
      { key: 'replacement_due_date', label: 'Replacement Due', type: 'date' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  maintenance: {
    title: 'Maintenance Schedule',
    description: 'Manage preventive maintenance, recurring tasks, owner assignment, and overdue work.',
    color: '#F59E0B',
    primary: 'task_name',
    columns: ['task_name', 'asset_tag', 'well_name', 'maintenance_type', 'frequency', 'next_due_date', 'status'],
    fields: [
      { key: 'task_name', label: 'Task Name', required: true },
      { key: 'asset_tag', label: 'Asset Tag' },
      { key: 'well_name', label: 'Well Name' },
      { key: 'maintenance_type', label: 'Maintenance Type', type: 'select', options: ['Preventive', 'Corrective', 'Inspection', 'Calibration', 'Regulatory'] },
      { key: 'frequency', label: 'Frequency', type: 'select', options: ['Daily', 'Weekly', 'Monthly', 'Quarterly', 'Semiannual', 'Annual', 'Condition Based'] },
      { key: 'next_due_date', label: 'Next Due Date', type: 'date' },
      { key: 'assigned_to', label: 'Assigned To' },
      { key: 'status', label: 'Status', type: 'select', options: ['Scheduled', 'Due Soon', 'Overdue', 'In Progress', 'Completed', 'Deferred'] },
      { key: 'instructions', label: 'Instructions', type: 'textarea' },
    ],
  },
  inspections: {
    title: 'Inspection Logs',
    description: 'Record field, safety, equipment, environmental, and pipeline inspections.',
    color: '#10B981',
    primary: 'inspection_type',
    columns: ['inspection_type', 'site_name', 'well_name', 'inspector', 'inspection_date', 'status', 'next_inspection_date'],
    fields: [
      { key: 'inspection_type', label: 'Inspection Type', required: true, type: 'select', options: ['Safety', 'Environmental', 'Equipment', 'Pipeline', 'Wellsite', 'Tank Battery'] },
      { key: 'site_name', label: 'Site Name', required: true },
      { key: 'well_name', label: 'Well Name' },
      { key: 'inspector', label: 'Inspector' },
      { key: 'inspection_date', label: 'Inspection Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['Open', 'Passed', 'Finding', 'Failed', 'Closed'] },
      { key: 'findings', label: 'Findings', type: 'textarea' },
      { key: 'corrective_action', label: 'Corrective Action', type: 'textarea' },
      { key: 'next_inspection_date', label: 'Next Inspection', type: 'date' },
    ],
  },
  permits: {
    title: 'Compliance Permits',
    description: 'Track permits, agencies, deadlines, operating requirements, and owners.',
    color: '#22C55E',
    primary: 'permit_number',
    columns: ['permit_number', 'permit_type', 'site_name', 'agency', 'status', 'expiration_date', 'owner'],
    fields: [
      { key: 'permit_number', label: 'Permit Number', required: true },
      { key: 'permit_type', label: 'Permit Type', required: true, type: 'select', options: ['Air', 'Water', 'Waste', 'Drilling', 'Discharge', 'Flaring', 'Pipeline'] },
      { key: 'site_name', label: 'Site Name' },
      { key: 'agency', label: 'Agency' },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'Pending', 'Expiring Soon', 'Expired', 'Suspended'] },
      { key: 'issue_date', label: 'Issue Date', type: 'date' },
      { key: 'expiration_date', label: 'Expiration Date', type: 'date' },
      { key: 'owner', label: 'Owner' },
      { key: 'requirements', label: 'Requirements', type: 'textarea' },
    ],
  },
  'crews-vendors': {
    title: 'Crews & Vendors',
    description: 'Manage field crews, service vendors, certifications, and assigned operating areas.',
    color: '#60A5FA',
    primary: 'name',
    columns: ['name', 'organization_type', 'role', 'status', 'assigned_area', 'phone', 'email'],
    fields: [
      { key: 'name', label: 'Name', required: true },
      { key: 'organization_type', label: 'Organization Type', type: 'select', options: ['Crew', 'Vendor', 'Contractor', 'Operator', 'Inspector'] },
      { key: 'role', label: 'Role' },
      { key: 'phone', label: 'Phone' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'On Call', 'Unavailable', 'Inactive'] },
      { key: 'certifications', label: 'Certifications', type: 'textarea' },
      { key: 'assigned_area', label: 'Assigned Area' },
    ],
  },
  inventory: {
    title: 'Inventory & Parts',
    description: 'Track spare parts, suppliers, reorder levels, quantities, and warehouse location.',
    color: '#F97316',
    primary: 'part_name',
    columns: ['part_number', 'part_name', 'category', 'quantity_on_hand', 'reorder_level', 'warehouse_location', 'status'],
    fields: [
      { key: 'part_number', label: 'Part Number', required: true },
      { key: 'part_name', label: 'Part Name', required: true },
      { key: 'category', label: 'Category', type: 'select', options: ['Pump', 'Valve', 'Sensor', 'Electrical', 'Chemical', 'Pipe', 'Safety', 'General'] },
      { key: 'quantity_on_hand', label: 'Quantity On Hand', type: 'number' },
      { key: 'reorder_level', label: 'Reorder Level', type: 'number' },
      { key: 'unit_cost_usd', label: 'Unit Cost ($)', type: 'number' },
      { key: 'warehouse_location', label: 'Warehouse Location' },
      { key: 'supplier', label: 'Supplier' },
      { key: 'status', label: 'Status', type: 'select', options: ['Available', 'Low Stock', 'Backordered', 'Reserved', 'Obsolete'] },
    ],
  },
  documents: {
    title: 'Documents',
    description: 'Track manuals, permits, inspection PDFs, procedures, reports, and evidence links.',
    color: '#CBD5E1',
    primary: 'document_title',
    columns: ['document_title', 'document_type', 'related_entity', 'owner', 'status', 'expiration_date'],
    fields: [
      { key: 'document_title', label: 'Document Title', required: true },
      { key: 'document_type', label: 'Document Type', type: 'select', options: ['Manual', 'Permit', 'Inspection', 'Procedure', 'Report', 'Contract', 'Evidence'] },
      { key: 'related_entity', label: 'Related Entity' },
      { key: 'owner', label: 'Owner' },
      { key: 'status', label: 'Status', type: 'select', options: ['Draft', 'Current', 'Expired', 'Under Review', 'Archived'] },
      { key: 'effective_date', label: 'Effective Date', type: 'date' },
      { key: 'expiration_date', label: 'Expiration Date', type: 'date' },
      { key: 'file_url', label: 'File URL' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  notifications: {
    title: 'Notification Center',
    description: 'Track alert delivery, acknowledgements, escalation status, and recipients.',
    color: '#EF4444',
    primary: 'title',
    columns: ['title', 'channel', 'recipient', 'severity', 'status', 'sent_at', 'acknowledged_at'],
    fields: [
      { key: 'title', label: 'Title', required: true },
      { key: 'channel', label: 'Channel', type: 'select', options: ['In-App', 'Email', 'SMS', 'Slack', 'PagerDuty', 'Webhook'] },
      { key: 'recipient', label: 'Recipient' },
      { key: 'severity', label: 'Severity', type: 'select', options: ['Low', 'Medium', 'High', 'Critical'] },
      { key: 'status', label: 'Status', type: 'select', options: ['Pending', 'Sent', 'Acknowledged', 'Failed', 'Escalated'] },
      { key: 'sent_at', label: 'Sent At', type: 'datetime-local' },
      { key: 'acknowledged_at', label: 'Acknowledged At', type: 'datetime-local' },
      { key: 'related_record', label: 'Related Record' },
      { key: 'message', label: 'Message', type: 'textarea' },
    ],
  },
  settings: {
    title: 'Settings',
    description: 'Configure thresholds, units, data-retention behavior, notification defaults, and integrations.',
    color: '#94A3B8',
    primary: 'setting_key',
    columns: ['setting_group', 'setting_key', 'setting_value', 'updated_by', 'updated_at'],
    fields: [
      { key: 'setting_group', label: 'Setting Group', required: true, type: 'select', options: ['Production', 'Maintenance', 'Alerts', 'Compliance', 'Units', 'Security', 'Integrations'] },
      { key: 'setting_key', label: 'Setting Key', required: true },
      { key: 'setting_value', label: 'Setting Value' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'updated_by', label: 'Updated By' },
    ],
  },
  wells: {
    title: 'Well Master Data',
    description: 'Maintain normalized well identity, operator, location, lifecycle dates, and operating status.',
    color: '#38BDF8',
    primary: 'well_name',
    columns: ['well_name', 'api_number', 'field_name', 'operator', 'well_type', 'status', 'first_production_date'],
    fields: [
      { key: 'well_name', label: 'Well Name', required: true },
      { key: 'api_number', label: 'API Number' },
      { key: 'field_name', label: 'Field Name' },
      { key: 'operator', label: 'Operator' },
      { key: 'well_type', label: 'Well Type', type: 'select', options: ['Horizontal', 'Vertical', 'Directional', 'Injection', 'Disposal'] },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'Inactive', 'Shut-in', 'Drilling', 'Completed', 'Plugged'] },
      { key: 'spud_date', label: 'Spud Date', type: 'date' },
      { key: 'first_production_date', label: 'First Production', type: 'date' },
      { key: 'latitude', label: 'Latitude', type: 'number' },
      { key: 'longitude', label: 'Longitude', type: 'number' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  targets: {
    title: 'Production Targets',
    description: 'Set monthly oil, gas, water, and uptime targets by well and owner.',
    color: '#06B6D4',
    primary: 'well_name',
    columns: ['well_name', 'target_month', 'oil_target_bpd', 'gas_target_mcfd', 'uptime_target_pct', 'owner', 'status'],
    fields: [
      { key: 'well_name', label: 'Well Name', required: true },
      { key: 'target_month', label: 'Target Month', required: true, type: 'date' },
      { key: 'oil_target_bpd', label: 'Oil Target (BPD)', type: 'number' },
      { key: 'gas_target_mcfd', label: 'Gas Target (MCFD)', type: 'number' },
      { key: 'water_limit_bpd', label: 'Water Limit (BPD)', type: 'number' },
      { key: 'uptime_target_pct', label: 'Uptime Target (%)', type: 'number' },
      { key: 'owner', label: 'Owner' },
      { key: 'status', label: 'Status', type: 'select', options: ['Draft', 'Approved', 'Active', 'Missed', 'Met', 'Archived'] },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  handovers: {
    title: 'Shift Handovers',
    description: 'Capture operator-to-operator handover notes, open issues, completed work, and safety concerns.',
    color: '#FBBF24',
    primary: 'shift_name',
    columns: ['shift_date', 'shift_name', 'area', 'outgoing_operator', 'incoming_operator', 'status'],
    fields: [
      { key: 'shift_date', label: 'Shift Date', required: true, type: 'date' },
      { key: 'shift_name', label: 'Shift Name', type: 'select', options: ['Day Shift', 'Night Shift', 'Swing Shift', 'Weekend Coverage'] },
      { key: 'outgoing_operator', label: 'Outgoing Operator', required: true },
      { key: 'incoming_operator', label: 'Incoming Operator' },
      { key: 'area', label: 'Area' },
      { key: 'open_issues', label: 'Open Issues', type: 'textarea' },
      { key: 'completed_work', label: 'Completed Work', type: 'textarea' },
      { key: 'safety_notes', label: 'Safety Notes', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['Open', 'Submitted', 'Reviewed', 'Closed'] },
    ],
  },
  approvals: {
    title: 'Approval Workflows',
    description: 'Control approvals for high-risk deletes, work orders, capital requests, exports, and compliance changes.',
    color: '#818CF8',
    primary: 'request_title',
    columns: ['request_title', 'request_type', 'requested_by', 'approver', 'priority', 'status', 'due_date'],
    fields: [
      { key: 'request_title', label: 'Request Title', required: true },
      { key: 'request_type', label: 'Request Type', required: true, type: 'select', options: ['Work Order', 'Capital Spend', 'Record Delete', 'Compliance Change', 'Data Export', 'Settings Change'] },
      { key: 'requested_by', label: 'Requested By' },
      { key: 'approver', label: 'Approver' },
      { key: 'status', label: 'Status', type: 'select', options: ['Pending', 'Approved', 'Rejected', 'Needs Info', 'Cancelled'] },
      { key: 'priority', label: 'Priority', type: 'select', options: ['Low', 'Medium', 'High', 'Critical'] },
      { key: 'due_date', label: 'Due Date', type: 'date' },
      { key: 'related_record', label: 'Related Record' },
      { key: 'business_justification', label: 'Business Justification', type: 'textarea' },
    ],
  },
  integrations: {
    title: 'Integrations & Webhooks',
    description: 'Track external systems, webhook endpoints, sync status, owners, and retry policies.',
    color: '#2DD4BF',
    primary: 'integration_name',
    columns: ['integration_name', 'integration_type', 'status', 'auth_type', 'last_sync_at', 'owner'],
    fields: [
      { key: 'integration_name', label: 'Integration Name', required: true },
      { key: 'integration_type', label: 'Integration Type', required: true, type: 'select', options: ['SCADA', 'IIoT', 'Slack', 'PagerDuty', 'ERP', 'Data Lake', 'Webhook'] },
      { key: 'endpoint_url', label: 'Endpoint URL' },
      { key: 'auth_type', label: 'Auth Type', type: 'select', options: ['None', 'API Key', 'OAuth', 'Basic', 'mTLS'] },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'Paused', 'Failed', 'Testing', 'Retired'] },
      { key: 'last_sync_at', label: 'Last Sync At', type: 'datetime-local' },
      { key: 'owner', label: 'Owner' },
      { key: 'retry_policy', label: 'Retry Policy' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  reports: {
    title: 'Operational Reports',
    description: 'Schedule and track production, maintenance, compliance, inventory, and executive reports.',
    color: '#E2E8F0',
    primary: 'report_name',
    columns: ['report_name', 'report_type', 'schedule', 'owner', 'status', 'next_run_at', 'delivery_channel'],
    fields: [
      { key: 'report_name', label: 'Report Name', required: true },
      { key: 'report_type', label: 'Report Type', required: true, type: 'select', options: ['Production', 'Maintenance', 'Compliance', 'Inventory', 'Safety', 'Executive'] },
      { key: 'schedule', label: 'Schedule', type: 'select', options: ['Daily', 'Weekly', 'Monthly', 'Quarterly', 'On Demand'] },
      { key: 'owner', label: 'Owner' },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'Paused', 'Failed', 'Draft', 'Archived'] },
      { key: 'last_run_at', label: 'Last Run At', type: 'datetime-local' },
      { key: 'next_run_at', label: 'Next Run At', type: 'datetime-local' },
      { key: 'delivery_channel', label: 'Delivery Channel', type: 'select', options: ['In-App', 'Email', 'Slack', 'SFTP', 'Download'] },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  'audit-trail': {
    title: 'Audit Trail',
    description: 'Review create, update, and delete events across operational records.',
    color: '#F43F5E',
    primary: 'summary',
    readOnly: true,
    columns: ['action', 'entity_table', 'entity_id', 'actor', 'summary', 'created_at'],
    fields: [
      { key: 'action', label: 'Action' },
      { key: 'entity_table', label: 'Entity Table' },
      { key: 'entity_id', label: 'Entity ID' },
      { key: 'actor', label: 'Actor' },
      { key: 'summary', label: 'Summary', type: 'textarea' },
    ],
  },
};

export const getOperationResource = (key) => OPERATION_RESOURCES[key];

const DEFAULT_AI_ACTIONS = [
  { key: 'summary', label: 'AI Summary' },
  { key: 'next_actions', label: 'Next Actions' },
];

export const OPERATION_AI_ACTIONS = {
  'work-orders': [
    { key: 'prioritization', label: 'Prioritize' },
    { key: 'risk', label: 'Delay Risk' },
    { key: 'next_actions', label: 'Field Plan' },
    { key: 'completion_notes', label: 'Completion Notes' },
  ],
  assets: [
    { key: 'lifecycle', label: 'Lifecycle Risk' },
    { key: 'replacement', label: 'Replacement Plan' },
    { key: 'maintenance_strategy', label: 'Maintenance Strategy' },
  ],
  maintenance: [
    { key: 'optimize_schedule', label: 'Optimize Schedule' },
    { key: 'risk', label: 'Deferral Risk' },
    { key: 'draft_work_order', label: 'Draft Work Order' },
  ],
  inspections: [
    { key: 'corrective_action', label: 'Corrective Action' },
    { key: 'risk', label: 'Finding Severity' },
    { key: 'draft_work_order', label: 'Create Work Order Plan' },
  ],
  permits: [
    { key: 'renewal_checklist', label: 'Renewal Checklist' },
    { key: 'risk', label: 'Compliance Risk' },
    { key: 'evidence_request', label: 'Evidence Request' },
  ],
  'crews-vendors': [
    { key: 'vendor_fit', label: 'Assignment Fit' },
    { key: 'risk', label: 'Availability Risk' },
    { key: 'next_actions', label: 'Dispatch Plan' },
  ],
  inventory: [
    { key: 'reorder', label: 'Reorder Plan' },
    { key: 'criticality', label: 'Criticality Score' },
    { key: 'supplier_risk', label: 'Supplier Risk' },
  ],
  documents: [
    { key: 'document_review', label: 'Document Review' },
    { key: 'evidence_request', label: 'Evidence Gaps' },
    { key: 'summary', label: 'Executive Summary' },
  ],
  notifications: [
    { key: 'escalation', label: 'Escalation Plan' },
    { key: 'risk', label: 'Response Risk' },
    { key: 'summary', label: 'Incident Brief' },
  ],
  settings: [
    { key: 'config_review', label: 'Config Review' },
    { key: 'risk', label: 'Control Risk' },
    { key: 'next_actions', label: 'Change Plan' },
  ],
  wells: [
    { key: 'data_quality', label: 'Data Quality' },
    { key: 'summary', label: 'Well Brief' },
    { key: 'next_actions', label: 'Ops Follow-up' },
  ],
  targets: [
    { key: 'target_variance', label: 'Target Review' },
    { key: 'risk', label: 'Miss Risk' },
    { key: 'next_actions', label: 'Recovery Plan' },
  ],
  handovers: [
    { key: 'handover_brief', label: 'Shift Brief' },
    { key: 'risk', label: 'Open Risk' },
    { key: 'next_actions', label: 'Next Shift Plan' },
  ],
  approvals: [
    { key: 'decision_brief', label: 'Decision Brief' },
    { key: 'risk', label: 'Approval Risk' },
    { key: 'next_actions', label: 'Follow-up Plan' },
  ],
  integrations: [
    { key: 'troubleshooting', label: 'Troubleshoot' },
    { key: 'risk', label: 'Integration Risk' },
    { key: 'next_actions', label: 'Recovery Plan' },
  ],
  reports: [
    { key: 'report_brief', label: 'Report Brief' },
    { key: 'risk', label: 'Delivery Risk' },
    { key: 'next_actions', label: 'Fix Plan' },
  ],
  'audit-trail': [
    { key: 'audit_review', label: 'Audit Review' },
    { key: 'risk', label: 'Control Risk' },
    { key: 'summary', label: 'Activity Summary' },
  ],
};

export const getOperationAiActions = (key) => OPERATION_AI_ACTIONS[key] || DEFAULT_AI_ACTIONS;
